# https://dev.to/kyleparisi/how-to-run-laravel-using-docker-iko
version: "2"
services:
        # app:
        #     image: kyleparisi/larasible
        #     ports:
        #       - 80:80
        #     environment:
        #       - APP_ENV=testing
        #     volumes:
        #       - ./:/var/www/default
        app:
            image: my_image
            ports:
              - 80:80
            environment:
              - APP_ENV=testing
            volumes:
              - ./:/var/www/default
            tty: true
            #command: 
            #  - nginx -g "daemon off";

        db:
            image: mysql:8.0.13
            entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password'] # https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_default_authentication_plugin
            restart: always
            environment:
                TZ: Europe/Rome
                MYSQL_DATABASE: myDb
                #    MYSQL_USER: root 
                MYSQL_PASSWORD: root
                MYSQL_ROOT_PASSWORD: root
            ports: 
                - "3306:3306"
     
        phpmyadmin:
            image: phpmyadmin/phpmyadmin
            links: 
                - db:db
            ports:
                - 8000:80
            environment:
                MYSQL_USER: root
                MYSQL_PASSWORD: root 
                MYSQL_ROOT_PASSWORD: root 
